Add Asynchronous
terasawakazuyuki/chat-space pull request #4
Opened 2019-01-27 10:47 UTC by terasawakazuyuki

非同期通信機能の実装

2019-01-27 11:33 UTC, terasawakazuyuki commented
#what
非同期通信機能の実装

#why
投稿が素早く出来、ユーザビリティの向上のため

2019-01-27 11:43 UTC, ghost requested changes

2019-01-27 11:43 UTC, hiroki5123 commented on app/assets/javascripts/message.js
> +                    <img src=${messageImage}>
画像がないときもimgタグが挿入されてしまうので、画像がないときはimgタグが挿入されないように修正しましょう

2019-01-27 11:43 UTC, hiroki5123 commented on app/views/messages/index.html.haml
> +        %ul.left-header__members
ここulである必要ありますか？

2019-01-28 05:10 UTC, terasawakazuyuki commented on app/views/messages/index.html.haml
> +        %ul.left-header__members
Memberの記述がおかしかったので訂正しました

2019-02-02 10:37 UTC, terasawakazuyuki commented on app/assets/javascripts/message.js
> +                    <img src=${messageImage}>
修正しました

2019-02-02 10:45 UTC, kuroko918 commented
いいかと思います！
LGTMです！

2019-02-02 10:46 UTC, merged